config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "spendtrac.com"
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'categories#index'
  resources :categories, only: [:index, :show, :new, :create, :destroy] do
    resources :expenditure, only: [:index]
  end

  resources :expenditures, only: [:new, :create, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(_user)
    can :manage, :all
    can :read, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :expenditures

  # Validations
  validates :name, presence: true, length: { maximum: 50 }
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  belongs_to :user
  belongs_to :category

  # Validations
  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :expenditures, dependent: :destroy

  # Validations
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 50 }
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: email_regex }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password password_confirmation current_password])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[name email password password_confirmation])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource except: %i[public]
  before_action :authenticate_user!, except: [:index]

  def index
    return unless current_user

    @user = current_user
    @categories = @user.categories.includes(:expenditures)
  end

  def show
    @category = Category.find(params[:id])
    @expenditures = @category.expenditures.order('created_at DESC')
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    if @category.save
      redirect_to categories_path
      flash[:notice] = 'Category created successfully'
    else
      flash[:alert] = 'Category not created'
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  def new
    @expenditure = Expenditure.new
  end

  def create
    @categories = params[:expenditure][:category_id].drop(1)
    @categories.each do |category|
      @expenditure = Expenditure.new(name: params[:expenditure][:name], amount: params[:expenditure][:amount],
                                     category_id: category.to_i, user_id: current_user.id)
      if @expenditure.save
        flash[:notice] = 'Expenditure created successfully'
        redirect_to category_path(category.to_i)
      else
        flash[:alert] = 'Expenditure not created'
        render :new
      end
    end
  end

  private

  def expenditure_params
    params.require(:expenditure).permit(:name, :amount, :category_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def splashscreen; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/index.html.erb
<% if current_user %>
  <div class="container-fluid d-flex flex-column align-items-center">
    <% unless @categories.empty? %>
      <% @categories.each do |category| %>
        <div class="card mt-2 mb-1 shadow p-3 bg-white rounded" style="width:100%;">
          <div class="card-body d-flex">
            <div>
              <img style="height: 40px; width:40px;" class="rounded-circle mx-2" src=<%= category.icon %> >
            </div>
            <div class="w-75 d-flex justify-content-between align-items-center mx-2">
              <div class="d-flex flex-column justify-content-center">
                <%= link_to "#{category.name}", category_path(category.id), class:"card-title category-name fs-5 stretched-link list-group-item" %>
                <p class="card-text mt-2"><small class="text-muted"><%=category.created_at.strftime("%d %b %Y")%></small></p>
              </div>
              <p class="card-text fw-semibold">$<%= category.expenditures.sum(:amount) %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h3 class="mt-4">You don't have any categories yet.</h2>
    <% end %>
    <%= link_to 'Add a new category', new_category_path, class: "btn btn-success mt-5 py-2 px-5 text-white fs-5" %>
  </div>
<% else %>
  <%= render partial: "shared/splashscreen" %>
<% end %> 

app/views/categories/new.html.erb
<div class="container-fluid w-100 d-flex flex-column align-items-center mt-5">
  <h1>Create a new category:</h1>
  <%= form_with model: @category, url: categories_path, method: :post, :html => {:class => "w-75 mt-4"} do |form| %>
    <div class="form-floating mb-3 w-100">
      <%= form.text_field :name, class:"form-control", id:"floatingInput", placeholder:"Category name" %>
      <%= form.label :name, 'Name', class: "form-label" %>
    </div>
    <div class="form-floating mb-3 w-100">
      <%= form.text_field :icon, class:"form-control", id:"floatingInput", placeholder:"Category icon"  %>
      <%= form.label :icon, 'Icon link', class: "form-label" %>
    </div>
    <%= form.submit 'Create category', class: "btn btn-success text-white", data:{turbo: false} %>
    <%= link_to "Back", categories_path, class: "btn btn-secondary"%>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="container-fluid d-flex flex-column align-items-center">
    <div class="card" style="width: 95%;">
      <div class="card-header">
        <div class="d-flex align-items-center">
          <img style="height: 40px; width:40px;" class="mx-2" src=<%= @category.icon %>>
          <h5 class="card-title category-name fs-5 stretched-link"><%=@category.name%>'s transactions</h5>
        </div>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex justify-content-between bg-light">
          <p class="m-1 gray-text fs-5">TOTAL SPENDING</p>
          <p class="fw-semibold m-1 gray-text fs-5">$<%= @expenditures.sum(:amount) %></p>
        </li>
        <% unless @expenditures.empty? %>
          <% @expenditures.each_with_index do |spen, expenditure| %>
            <li class="list-group-item">
              <div d-flex flex-column>
                <p class="card-text gray-text">Transaction N°<%=expenditure + 1%>: <span class="fw-semibold ms-2"><%=spen.name%></span></p>
                <p class="card-text gray-text">Amount: <span class="fw-semibold ms-2">$<%=spen.amount%></span></p>
                <p class="card-text mt-2"><small class="text-muted"><i class="fa-regular fa-calendar me-2"></i><%=spen.created_at.strftime("%d %b %Y")%> at <%=spen.created_at.strftime("%I.%M %p")%></small></p>
              </div>
            </li>
          <% end %>
        <% else %>
          <li class="list-group-item gray-text">You don't have any transactions yet.</li>
        <% end %>
      </ul>
    </div>
    <div>
      <%= link_to 'Add a new transaction', new_expenditure_path, class: "btn btn-success my-5 py-2 px-5 text-white fs-6" %>
      <%= link_to "Back", categories_path, class: "btn btn-secondary"%>
    </div> 
  </div>

app/views/expenditures/new.html.erb
<div class="container-fluid w-100 d-flex flex-column align-items-center mt-5">
    <h1>Create a new transaction:</h1>
    <%= form_with model: @expenditure, url: expenditures_path, method: :post, :html => {:class => "w-75 mt-4"} do |form| %>
      <div class="form-floating mb-3 w-100">
        <%= form.text_field :name, class:"form-control", id:"floatingInput", placeholder:"Transaction name" %>
        <%= form.label :name, 'Name', class: "form-label" %>
      </div>
      <div class="form-floating mb-3 w-100">
        <%= form.number_field :amount, class:"form-control", id:"floatingInput", placeholder:"Transaction amount"  %>
        <%= form.label :amount, 'Amount', class: "form-label" %>
      </div>
      <%= form.label :category_id, 'Please select a category (ctrl+click for multiple selection):', class: "form-label" %>
      <%= form.select :category_id, Category.order(:name).where(user:current_user).pluck(:name, :id), {}, {:multiple => true, required:true, :id => "categories", :class => "form-select mb-3" } %>
      <%= form.submit 'Create transaction', class: "btn btn-success text-white" %>
      <%= link_to "Back", categories_path, class: "btn btn-secondary"%>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spendtrac</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Bootstrap CSS %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="http://fonts.cdnfonts.com/css/proxima-nova-2" rel="stylesheet">
    <script src="https://kit.fontawesome.com/1dea6ac3ad.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="border border-dark" style="min-height: 100vh;">
    <% if current_user %>
      <%= render partial: "shared/navbar" %>
      <p class="username">Welcome <%= current_user.name %>!</p>
    <% end %>

    <div class="container">
      <%if flash[:notice]%><p class="notice alert alert-success"><%= notice %></p> <%end%>
      <%if flash[:alert]%> <p class="alert alert alert-danger"><%= alert %></p> <%end%>
      <%= yield %>
    </div>

  </body>
</html>

app/views/pages/splashscreen.html.erb
<h1>Pages#splashscreen</h1>
<p>Find me in app/views/pages/splashscreen.html.erb</p>

app/views/shared/_applogo.html.erb
<%= image_tag "spendtrac-logo.png", height: 120, width: 180, :alt => "spendtrac logo", :class => "d-block mx-auto mb-4" %>

app/views/shared/_navbar.html.erb
<div class="collapse text-white" id="navbarToggleExternalContent" style="background-color: #3778c2;">
    <div class="collapse navbar-collapse d-flex flex-column align-items-center" id="navbarTogglerDemo01">
      <%= render partial: "shared/applogo", class: "navbar-brand" %>
      <ul class="navbar-nav d-flex flex-column align-items-center me-auto mb-2 mb-lg-0 w-100">
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link active fs-6" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Categories", new_category_path, class: "nav-link active fs-6" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Transaction", new_expenditure_path, class: "nav-link active fs-6" %>
        </li>
      </ul>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger my-2" %>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-primary mb-2">
    <div class="container-fluid d-flex justify-content-between">
      <button class="menu-btn" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fa-solid fa-bars"></i></span>
      </button>
      <h1 class="appname">SpendTrac</h1>
      <h3 class="text-white mt-1">
        <% if controller.controller_name == 'groups' && controller.action_name != 'show' %> Categories <% end %>
        <% if (controller.controller_name == 'groups' && controller.action_name == 'show') || controller.controller_name == 'expenses' %> Transactions <% end %>
      </h3>
      <%= link_to '<i class="fa-regular fa-magnifying-glass"></i>'.html_safe, root_path %>
    </div>
  </nav>

app/views/shared/_splashscreen.html.erb
<div class="px-4 py-5 my-5 text-center">
  <%= render partial: "shared/applogo" %>
  <h1 class="display-5 fw-bold">SpendTrac App</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Keep track of your daily spending. SpendTrac made it all easy direct from your mobile phone.</p>

    <div class="d-grid gap-4 d-sm-flex justify-content-sm-center">
      <%= link_to "Log In", new_user_session_path, class: "btn btn-primary btn-lg px-4 gap-4" %> 
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-secondary btn-lg px-4" %> 
    </div>
  </div>
</div>